### ISSUE TITLE
Add networkpolicy

### ISSUE THREAD

**Issue by devopstales** [oauth2-proxy/manifests#103]
I tried to use the oauth proxy in a cluster where networkpolicy is enabled. The pod can not start and not logging anything.

I have the fallowing policies: 

```
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-internet-only
  namespace: ingress-system
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/component: authentication-proxy
      app.kubernetes.io/instance: oauth2-proxy
  policyTypes:
  - Egress
  egress:
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-to-oauth2-proxy--ingress-nginx-private--controller
  namespace: ingress-system
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/component: controller
      app.kubernetes.io/instance: ingress-nginx-private
  policyTypes:
  - Egress
  egress:
  - to:
    - podSelector:
        matchLabels:
          app.kubernetes.io/component: authentication-proxy
          app.kubernetes.io/instance: oauth2-proxy
```
