### ISSUE TITLE
Using Kubernetes secret for alpha configuration provider client secret

### ISSUE THREAD

**Issue by albert0815** [oauth2-proxy/manifests#104]
Hi,

When using alpha configuration it seems that using the "existingSecret" is not possible any more. As far as I understand we need to provide the secret of the client in plain text in the provider definition in the alpha configuration. Is this true?

Currently my configuration looks like similar to this:
```
alphaConfig:
          enabled: true
            providers:
              - id: Keycloak
                clientID: oauth2-gateway
                clientSecret: xxxxx
                provider: keycloak-oidc
                name: Keycloak
                oidcConfig:
                  issuerURL: https://keycloak-url
```

I want to know whether it would be possible to use something like this:
```
alphaConfig:
          enabled: true
            providers:
              - id: Keycloak
                existingSecret: keycloak-secret # <- is this possible? This would refer to a k8s secret similar to config.existingsecret.
                provider: keycloak-oidc
                name: Keycloak
                oidcConfig:
                  issuerURL: https://keycloak-url
```

If not, is this something which could be implemented in the chart?

Thanks
Dirk

**Comment by pierluigilenoci** [comment]
I'm sorry but the chart currently doesn't work like that.
Ref: https://github.com/oauth2-proxy/manifests/blob/main/helm/oauth2-proxy/templates/configmap-alpha.yaml#L14-L32

**Comment by albert0815** [comment]
Thank you for your response and the reference. As far as I understand it might actually not be the chart structure itself which is making this impossible. Since alpha configuration is provided as a file into the oauth2-proxy this could only work if oauth2-proxy would allow resolving data in the configuration file itself from environment variables.

If we could pass in something like this into oauth2-proxy:

```
- provider: oidc
  clientSecret: ${OIDC_SECRET_ENVIRONMENT_VARIABLE}
  clientID: oauth2-proxy
  oidcConfig:
    oidcIssuerURL: http://dex.localhost:4190/dex
```

Then it should also be possible to configure it based on the helm chart. Do you think this is something which could be done?
