### ISSUE TITLE
Oauth2-proxy Helm chart w/ NGINX ingress controller to enable SSO for Prometheus 

### ISSUE THREAD

**Issue by lexarflash8g** [oauth2-proxy/manifests#107]
How to configure Oauth2-proxy Helm chart values to work with AzureAD SSO for securing Prometheus endpoint.

Expected Behavior
Hitting Prometheus endpoint such as https://prometheus.mydomain.com/ should show splash page to use SSO with Oauth2-proxy to login to reach app.

Current Behavior
Oauth2-proxy Helm chart installed and configured with client_id and client_secret for Prometheus web app in AzureAD, and ingress EP created as well for Oauth2-proxy. I can reach https://oauth2-proxy.mydomain.com/ and there is a button to login via OIDC. Setting up annotations on Prometheus ingress shows 503 error. I'm using Prometheus-operator as part of Kube-prometheus-stack.

Oauth2 proxy splash page https://oauth2-proxy.mydomain.com/ :

![oauth2proxy](https://user-images.githubusercontent.com/10263702/185678785-bad5cde6-d3cc-4812-bccf-cafe749bc8a0.png)

image

After logging in via SSO:

image

![noreplyaddress](https://user-images.githubusercontent.com/10263702/185678818-c3917498-692a-4b6f-8a27-83734406efba.png)
e

Possible Solution
Perhaps wrong annotations -- or misconfigured Oauth2-proxy Helm values.

Steps to Reproduce (for bugs)
My ingress annotations for Prometheus:

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    meta.helm.sh/release-name: kube-prometheus-stack
    meta.helm.sh/release-namespace: monitoring
    # nginx.ingress.kubernetes.io/auth-response-headers: Authorization
    nginx.ingress.kubernetes.io/auth-url: "http://oauth2.mydomain.com/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "https://oauth2.mydomain.com/oauth2/start?rd=$request_uri" 


```

And Helm values for Oauth2 proxy.

```
config:
  # Add config annotations
  annotations: {}
  configFile: |-
    email_domains = [ "*" ]
    pass_basic_auth = false
    pass_access_token = true
    reverse_proxy = true
    provider = "oidc"
    oidc_issuer_url = "https://login.microsoftonline.com/$TENANT_ID/v2.0"
    # # custom_sign_in_logo = "/usr/local/share/azure_logo.png"
    footer = '-'
    client_id = "$MY_CLIENT_ID"
    client_secret = "$MY_CLIENT_SECRET"
    skip_auth_routes = [
      "GET=^/probe",
      "^/metrics"
    ]
    pass_user_headers = true
    pass_host_header = true
    set_xauthrequest = true
    cookie_expire = "168h"
    cookie_secure = false
    scope= "openid profile email"

```

## Context

Getting 503 error hitting Prometheus EP
and trying to login via Oauth2 EP results in : "No reply address provided."

The Callback URL for the app on the AzureAD side is: https://prometheus.mydomain.com/.

The Callback URL should be Prometheus correct? Not Oauth2 proxy -- i'm a bit confused about this part. 

## Your Environment

Using AWS EKS, with internal ELBs, and AzureAD for SSO.

- Version used:
https://artifacthub.io/packages/helm/oauth2-proxy/oauth2-proxy
with Helm version 6.2.2
