### ISSUE TITLE
Read redis sentinel password from same key as redis password

### ISSUE THREAD

**Issue by alexbde** [oauth2-proxy/manifests#115]
We're using the oauth2-proxy with a redis with activated sentinel. It's a default redis from the popular [bitnami redis chart](https://artifacthub.io/packages/helm/bitnami/redis).

To use the secret created by redis, we set `sessionStorage.redis.existingSecret` to the name of the existing secret. This is working for the redis password, because oauth2-proxy is expecting bitnami redis to provide a secret with the name `redis-password`, which it does: https://artifacthub.io/packages/helm/bitnami/redis?modal=template&template=secret.yaml

Sadly, it is not working for the redis sentinel password, because it is the same in bitnami redis and also called `redis-password`.

Is there a way to define the name of the password in the existing secret? Setting `sessionStorage.redis.sentinel.password` looks like the field I'm looking for, but is simply doing nothing.

Would it be an option to replace this line: https://github.com/oauth2-proxy/manifests/blob/b3b047c208d1053982154e1931cf2147d42a50c0/helm/oauth2-proxy/templates/deployment.yaml#L154

by
```
key: {{ .Values.sessionStorage.redis.sentinel.password | default "redis-sentinel-password" }}
```

We could simply use it setting `sessionStorage.redis.sentinel.password = "redis-password"`.

If you like this idea, I'll create a PR for it.

PS: we're using the following workaround in the mean time:

```
  extraEnv:
  - name: OAUTH2_PROXY_REDIS_SENTINEL_PASSWORD
    valueFrom:
      secretKeyRef:
        name: redis
        key: redis-password
```

**Comment by pierluigilenoci** [comment]
Hi @alexbde do you use the Redis chart in the OAuth2-Proxy chart or do you configure it with a separate chart?
Because using the integrated one makes things a lot easier to set up.

However, an easy way to do what you need should be to put the credentials in an external secret and use it on both sides.

OAuth Proxy side:
```yaml
  sessionStorage:
    type: redis
    redis:
      password: true
      existing secret: "redis-secret"
```
Redis side:
```yaml
    usePassword: true
    existingSecret: "redis-secret"
    existingSecretPasswordKey: "redis-password"
```

And then:
```shell
kubectl create secret generic redis-secret \
  --namespace <yournamespace> \
  --from-literal=redis-password=<yourpassword>
```

Maybe I didn't understand your problem well anyway if you want to do a PR feel free to do it.
