### ISSUE TITLE
Reference environment variable in oidc-issuer-url

### ISSUE THREAD

**Issue by deggja** [oauth2-proxy/manifests#131]
Hello guys,

I'm curious to know if there is any way to use environment variables to reference the oidc-issuer-url in the helm chart. What I am trying to achieve is to mount a variable from a secret and reference it as such:

**alternative one (mounting tenant id from secret):**
```
oidc-issuer-url: https://login.microsoftonline.com/${tenant}/v2.0
```

**alternative two (mounting entire url from secret):**
```
oidc-issuer-url: ${url}
```

I've tried both approaches but the error message is something of this sort:

```
[2023/02/03 12:14:30] [main.go:60] ERROR: Failed to initialise OAuth2 Proxy: error intiailising provider: could not create provider data: error building OIDC ProviderVerifier: could not get verifier builder: error while discovery OIDC configuration: failed to discover OIDC configuration: unexpected status "400": {"error":"invalid_tenant","error_description":"AADSTS90002: Tenant '${tenant}' not found. Check to make sure you have the correct tenant ID and are signing into the correct cloud. Check with your subscription administrator, this may happen if there are no active subscriptions for the tenant.
```

Not sure why this does not work. I have used the same approach when defining my Azure tenant in the same config and this works exactly as expected.

**Current configuration:**
```
extraArgs:
  provider: oidc
  azure-tenant: ${tenant}  # Azure AD OAuth2 Proxy application Tenant ID
  pass-access-token: true
  email-domain: "*"
  upstream: file:///dev/null
  http-address: 0.0.0.0:4180
  oidc-issuer-url: https://login.microsoftonline.com/${tenant}/v2.0
  session-store-type: redis
extraEnv:
  - name: oidc-issuer-tenant
    valueFrom:
      secretKeyRef:
        name: oidc-issuer-url
        key: tenant
  - name: oidc_issuer_url
    valueFrom:
      secretKeyRef:
        name: oidc-issuer-url
        key: url
```

Am I going about this the wrong way? My goal is to hide the tenant ID (and other sensitive information) from the values file itself.

Thanks.
