### ISSUE TITLE
Provide good securityContext by default

### ISSUE THREAD

**Issue by jemag** [oauth2-proxy/manifests#142]
**Describe the solution you'd like**
Provide good default for the various securityContext like:
```yaml
  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
      - ALL
    readOnlyRootFilesystem: true
    runAsGroup: 2000
    runAsNonRoot: true
    runAsUser: 2000
    seccompProfile:
      type: RuntimeDefault

```

Currently securityContext is not enabled, although some values are potentially suggested in comment, e.g:
```yaml
securityContext:
  enabled: false
  runAsNonRoot: true
  # allowPrivilegeEscalation: false
  # runAsUser: 2000
```
**What is the added value?**
This would improve the default security out of the box for helm chart users. If the containers currently support it, there isn't much downside to improving the default security.

It also helps clarifying to the end-user that these values are officially supported and will not cause any problem with the containers (e.g.: `readOnlyRootFilesystem: true` could for example cause problems for containers expecting to write to specific directories). By having them already specified, the end-user does not need to do extensive testing to ensure it does not cause any issue.
