### ISSUE TITLE
helm-chart: .Values.metrics.serviceMonitor.tlsConfig should have indent 6, and not 4

### ISSUE THREAD

**Issue by StianOvrevage** [oauth2-proxy/manifests#199]
It's currently not possible to use ServiceMonitor `tlsConfig` configuration due to incorrect indentation ( https://github.com/oauth2-proxy/manifests/blob/e4d9dd6803f2bd5be189db6be54ebcf554c14f19/helm/oauth2-proxy/templates/servicemonitor.yaml#L47 ) in the helm chart.

The indent should be changed from `4` to `6`.

(Note that this does not apply to `metricRelabelings` and `relabelings` since they are lists/slices and works correctly with 4).

    helm template my-oauth2-proxy oauth2-proxy/oauth2-proxy --values values-oauth2-proxy.yaml --show-only templates/servicemonitor.yaml

```
  endpoints:
  - port: metrics
    path: "/metrics"
    interval: 60s
    scrapeTimeout: 30s
    scheme: https
    tlsConfig:
    caFile: /etc/cert.pem                      # Should have one more indent
    certFile: /etc/chain.pem                   # Should have one more indent
    insecureSkipVerify: "true"                 # Should have one more indent
    keyFile: /etc/key.pem                      # Should have one more indent
    metricRelabelings:                  # Works correctly
    - action: keep
      regex: kube_(daemonset|deployment|pod|namespace|node|statefulset).+
      sourceLabels:
      - __name__
    relabelings:                        # Works correctly
    - action: replace
      regex: ^(.*)$
      replacement: $1
      separator: ;
      sourceLabels:
      - __meta_kubernetes_pod_node_name
      targetLabel: nodename
```

`values.yaml` (abbreviated):

```
metrics:
  serviceMonitor:
    # Enable Prometheus Operator ServiceMonitor
    enabled: true
    # Prometheus Instance definition
    prometheusInstance: default
    # Prometheus scrape interval
    interval: 60s
    ## scheme: HTTP scheme to use for scraping. Can be used with `tlsConfig` for example if using istio mTLS.
    scheme: "https"

    ## tlsConfig: TLS configuration to use when scraping the endpoint. For example if using istio mTLS.
    ## Of type: https://github.com/coreos/prometheus-operator/blob/master/Documentation/api.md#tlsconfig
    tlsConfig:
        caFile: /etc/cert.pem
        certFile: /etc/chain.pem
        insecureSkipVerify: "true"
        keyFile: /etc/key.pem

    metricRelabelings:
    - action: keep
      regex: 'kube_(daemonset|deployment|pod|namespace|node|statefulset).+'
      sourceLabels: [__name__]

    relabelings: 
    - sourceLabels: [__meta_kubernetes_pod_node_name]
      separator: ;
      regex: ^(.*)$
      targetLabel: nodename
      replacement: $1
      action: replace
```
