### ISSUE TITLE
wait-for-redis fails to detect redis with default image

### ISSUE THREAD

**Issue by lmsurpre** [oauth2-proxy/manifests#213]
### OAuth2-Proxy Version

helm chart version 7.7.1

### Expected Behaviour

Configuring the helm chart to work with the redis subchart should work with the default waitForRedis container image.

### Current Behaviour

When configured to work with redis, the deployment never becomes healthy because the wait-for-redis initContainer just spins its wheels:

```sh
$ kubectl logs -f lee-oauth2-proxy-79cb74fcb9-2kdk9 -c wait-for-redis                        
Checking standalone Redis...
Checking Redis at lee-redis-master:6379... Elapsed time: 0s
Redis is down at lee-redis-master:6379. Retrying in 5 seconds.
Checking Redis at lee-redis-master:6379... Elapsed time: 5s
Redis is down at lee-redis-master:6379. Retrying in 5 seconds.
Checking Redis at lee-redis-master:6379... Elapsed time: 10s
Redis is down at lee-redis-master:6379. Retrying in 5 seconds.
...
Redis is down at lee-redis-master:6379. Retrying in 5 seconds.
Checking Redis at lee-redis-master:6379... Elapsed time: 145s
```

But redis seems to be up and healthy.

When I try to inspect whats going wrong, it looks to me like its trying to run [netcat command](https://github.com/oauth2-proxy/manifests/blob/main/helm/oauth2-proxy/scripts/check-redis.sh#L11) to wait for redis, but it doesn't seem like the default image (bitnami/kubectl) defined by the chart even has netcat installed.

```sh
$ docker run -it --entrypoint "/bin/bash" bitnami/kubectl      
I have no name!@818c61fb65df:/$ nc
bash: nc: command not found
```

Note that when I run the same helm deploy with `initContainers.waitForRedis.enabled = false` then the deploy succeeds.
However, I'd prefer to have this set to true because when its false the oauth2-proxy pod errors out and restarts a few times while redis is coming up.

### Steps To Reproduce

1. with the latest version of the helm chart (7.7.1)
2. with `sessionStorage.type = redis`, `redis.enabled = true`, and `initContainers.waitForRedis.enabled = true`
3. perform the helm deploy and monitor the status

### Possible Solutions

Use a different base image, such as alpine, that actually includes netcat.
Alternatively, update the check-redis.sh script to use an alternative command for checking that redis is listening.

### Configuration details or additional information
Previously I was using version 6.23.1 of the helm chart and it was working with the same config.
I tried reviewing the release notes from 7.x and beyond, but couldn't tell if there is something I'm supposed to change or not.

Select snippets from my override.yaml:
```
  httpScheme: https
  service:
    appProtocol: https
    portNumber: 443
  extraArgs:
    # cookie_refresh > 0 requires oauth tokens in sessions. session_cookie_minimal cannot be set
    cookie-refresh: 10m
    cookie-expire: 30m
    redis-insecure-skip-tls-verify: "true"
  # refer to https://oauth2-proxy.github.io/oauth2-proxy/docs/configuration/alpha-config/
  alphaConfig:
    enabled: true
    ...
  sessionStorage:
    type: redis
  # use a redis subchart
  redis:
    enabled: true
    tls:
      enabled: true
      authClients: false
      autoGenerated: true
    master:
      affinity:
      persistence:
        enabled: false
      containerSecurityContext:
        runAsNonRoot: true
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
    replica:
      affinity:
      persistence:
        enabled: false
      containerSecurityContext:
        runAsNonRoot: true
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
```

**Comment by lmsurpre** [comment]
when I override the waitForRedis image with the stock alpine image, it works just fine (with the same exact config):

```
  initContainers:
    waitForRedis:
      enabled: true
      image:
        repository: alpine
```

How do folks feel about changing the default?
