### ISSUE TITLE
Redis Standalone default redis password is set on two different locations

### ISSUE THREAD

**Issue by JcGKitten** [oauth2-proxy/manifests#225]
After spending some time to figure that out, I wanted to ask if this is intended or a bug.

When using `Redis` with `clientType.standalone` configure redis via values like suggested in this [comment](https://github.com/oauth2-proxy/manifests/issues/154#issuecomment-1622197960):
```yaml
redis:
  enabled: true
sessionStorage:
  type: redis
  redis:
    password: "XXXXXXX"
```
isn't working and shows the following logs in the `oauth` pod:
```
  unable to set a redis initialization key: WRONGPASS invalid username-password pair or user is disabled.
  unable to delete the redis initialization key: WRONGPASS invalid username-password pair or user is disabled.
```

I discovered in the [redis-standalone-values.yaml](https://github.com/oauth2-proxy/manifests/blob/main/helm/oauth2-proxy/ci/redis-standalone-values.yaml) that the password for redis is also set under `redis.global.redis.password`. After setting this password:
```yaml
redis:
  enabled: true
  global:
    redis:
      password: "XXXXXXX"
sessionStorage:
  type: redis
  redis:
    password: "XXXXXXX"
```
Oauth Proxy can connect to redis and the storage works. So I was wondering if this should be mentioned in the README or if this a bug.

**Comment by pierluigilenoci** [comment]
@JcGKitten This is because the password must be set in this chart and inside the Redis sub-charts.
There is no way to do otherwise. Is it more clear?

Ref: 
* https://github.com/oauth2-proxy/manifests/blob/main/helm/oauth2-proxy/Chart.yaml#L15-L20
* https://github.com/bitnami/charts/blob/main/bitnami/redis/values.yaml#L26

**Comment by JcGKitten** [comment]
@pierluigilenoci  yes it's more clear now, thx. Hope this issue might help others come across this, but closing it now, cause all needed information is given.

**Comment by max-pfeiffer** [comment]
> [@JcGKitten](https://github.com/JcGKitten) This is because the password must be set in this chart and inside the Redis sub-charts. There is no way to do otherwise. Is it more clear?
> 
> Ref:
> 
> * https://github.com/oauth2-proxy/manifests/blob/main/helm/oauth2-proxy/Chart.yaml#L15-L20
> * https://github.com/bitnami/charts/blob/main/bitnami/redis/values.yaml#L26

Not really. 😃 

I just fell into the same trap.

**Comment by tuunit** [comment]
I guess it is just inconvenient for people to realize that the redis password has to be set inside `sessionStorage.redis...` and `redis.global....`

Can we maybe get this automated / templated through a helper function?

couldn't we just use `.Values.redis.global.password` as the source for the session storage password?

**Comment by max-pfeiffer** [comment]
@pierluigilenoci At first glance the correlation between these two settings was not clear to me. And I going through the chart's source and read the comments in values.yaml. Plus I am not so familiar with that Bitnami Redis chart. I could have done more digging to find out myself. But then I found this thread in the issues. 😄 

I just sent you a pull request to improve the documentation in values.yaml a bit: https://github.com/oauth2-proxy/manifests/pull/283
With these comments I would have been more clear to me. 

@tuunit That would be perfect! I would have more time, I would be glad to help here.

BTW: thanks a lot guys for maintaining this chart! It's very useful for me. Much appreciated.

**Comment by pierluigilenoci** [comment]
@tuunit I understand the inconvenience, but we are dealing with a main chart and a sub-chart, and there is not much we can do about that.

It might make sense to use the parameters from the sub-chart to configure our credentials; however, we need to ensure that this configuration is possible even when the sub-chart is inactive. Valorizing a parameter from an inactive sub-chart solely to have it on our side does not seem like an elegant solution.

**Comment by Baibhav168** [comment]
Another issue similar to this when using existingSecret instead. Redis Sub chart takes decrypted value from this without the new-line, while oauth2 takes exactly with new-line causing password mismatch. So make sure the decrypted value from `oauth2-proxy-redis-custom` doesnt contain any `\n`

```
redis:
  enabled: true
  auth:
    enabled: true
    existingSecret: "oauth2-proxy-redis-custom"   # <-- Your secret name
    usePasswordFileFromSecret: true

sessionStorage:
  type: redis
  redis:
    existingSecret: "oauth2-proxy-redis-custom"   # <-- Same secret name
    passwordKey: "redis-password"                 # <-- Key in the secret (default)
```
