### ISSUE TITLE
Allow using templates in annotations

### ISSUE THREAD

**Issue by gtudan** [oauth2-proxy/manifests#254]
I have a use case where I need to include helm templates in an annotation. Example:

```yaml
  ingress: 
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/custom-http-errors: "401,403,404,500,502,503"
      nginx.ingress.kubernetes.io/default-backend: "{{ .Release.Name }}-error-pages"
```

This does not work as of now - the "{{ .Release.Name }}"-part is not interpreted and written as is to the rendered manifest.
