### ISSUE TITLE
redis.existingSecret doesn't take effect when redis.password is set to empty string

### ISSUE THREAD

**Issue by coy2k** [oauth2-proxy/manifests#78]
Can't use an existingSecret for redis session storage in order to set OAUTH2_PROXY_REDIS_PASSWORD when the password has a empty string assigned.

Doesn't work:
```yaml
# values.yaml
...
sessionStorage:
  type: redis
  redis:
    existingSecret: oauth2-proxy-redis-access
    password: ""
...
```

Works:
```yaml
# values.yaml
...
sessionStorage:
  type: redis
  redis:
    existingSecret: oauth2-proxy-redis-access
    password: someValue
...
```

Fix suggestion:
```yaml
# templates/deployment.yaml
...
        {{- if or .Values.sessionStorage.redis.password .Values.sessionStorage.redis.existingSecret }}
        - name: OAUTH2_PROXY_REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ if .Values.sessionStorage.redis.existingSecret }} {{ .Values.sessionStorage.redis.existingSecret }}{{ else }} {{ template "oauth2-proxy.fullname" . }}-redis-access{{ end }}
              key: redis-password
        {{- end }}
...
```
