### ISSUE TITLE
use redis subchart pwd secret if no existing secret or password was set

### ISSUE THREAD

**Issue by bluebrown** [oauth2-proxy/manifests#84]
It would be nice that when the redis subchart is enabled and has auth enabled, the password would be read from the secret that is created by the redis subchart. 

This would remove the need to set the password twice or reference the secret which name is dependent on the release name. It would make the integreation with redis more straight forward and should work out of the box for most use cases.

If implemented, the redis integration via subchart would require only the below values to work. 

```yaml
sessionStorage:
  type: redis
redis:
  enabled: true
  auth:
    password: foobar
```
