### ISSUE TITLE
Service targetPort incorrect

### ISSUE THREAD

**Issue by endakelly** [oauth2-proxy/manifests#86]
When creating a helm release from this chart, the upstream service doesn't load at all unless the service targetPort is edited. My httpScheme value is set to https. To get the static upstream page to work, I have to edit the service and change the targetPort from https to 4443.

After this, the page loads successfully.

**Before:** 
  
ports:
  - name: https
    nodePort: 31936
    port: 443
    protocol: TCP
    targetPort: https

![image](https://user-images.githubusercontent.com/80516065/154967320-dfac8746-92e0-4db1-8cea-330cae05d8ae.png)

**After:**

  ports:
  - name: https
    nodePort: 31936
    port: 443
    protocol: TCP
    targetPort: 4443

![image](https://user-images.githubusercontent.com/80516065/154967517-ba769c61-02cc-4ed8-9ce2-410404024a13.png)

**Comment by bluebrown** [comment]
Where does this port name even come from in the first place? I cannot find it i[n the chart](https://github.com/oauth2-proxy/manifests/blob/main/helm/oauth2-proxy/templates/service.yaml). What version of the cart are you using?

Service has those ports:

```yaml
  ports:
    - port: {{ .Values.service.portNumber }}
      targetPort: {{ .Values.httpScheme }}
      protocol: TCP
      name: {{ .Values.httpScheme }}
    {{- if and .Values.metrics.enabled .Values.metrics.port }}
    - port: {{ .Values.metrics.port }}
      protocol: TCP
      targetPort: metrics
      name: metrics
    {{- end }}
```

The value for `httpScheme` is http, and it points to `service.portNumber` which is 80 by default.
